# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f363ba40a9ec959cf1b51f32c529c2f63fa38c21787daf4f4a7762766a776238a8797d6d81a72c58aa19b90a6b39306afc47a34980ce4bd7ce8ffcd97868d5b0

test:
  secret_key_base: 672550422b533b98b4f78696b000688380d22f63f13c9ae32a3c8f02bb30e4f12e47f88e535a0175f23d3c96d3b5fcf5baa156786c8366a11f48a9f22acce359

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
